USE [master]
GO
/****** Object:  Database [JUEVES_BD]    Script Date: 12/6/2024 22:44:38 ******/
CREATE DATABASE [JUEVES_BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JUEVES_BD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\JUEVES_BD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JUEVES_BD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\JUEVES_BD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [JUEVES_BD] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JUEVES_BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JUEVES_BD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JUEVES_BD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JUEVES_BD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JUEVES_BD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JUEVES_BD] SET ARITHABORT OFF 
GO
ALTER DATABASE [JUEVES_BD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JUEVES_BD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JUEVES_BD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JUEVES_BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JUEVES_BD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JUEVES_BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JUEVES_BD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JUEVES_BD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JUEVES_BD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JUEVES_BD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JUEVES_BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JUEVES_BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JUEVES_BD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JUEVES_BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JUEVES_BD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JUEVES_BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JUEVES_BD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JUEVES_BD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JUEVES_BD] SET  MULTI_USER 
GO
ALTER DATABASE [JUEVES_BD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JUEVES_BD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JUEVES_BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JUEVES_BD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JUEVES_BD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JUEVES_BD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [JUEVES_BD] SET QUERY_STORE = ON
GO
ALTER DATABASE [JUEVES_BD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [JUEVES_BD]
GO
/****** Object:  Table [dbo].[tUsuario]    Script Date: 12/6/2024 22:44:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tUsuario](
	[Consecutivo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Correo] [varchar](100) NOT NULL,
	[Contrasenna] [varchar](100) NOT NULL,
	[IdRol] [tinyint] NOT NULL,
	[Estado] [bit] NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [JUEVES_BD] SET  READ_WRITE 
GO
